### ISSUE TITLE
create a header file Like comment to trigger VVDocumenter in Xcode Version 6.3.1 ,and xcode not responding

### ISSUE THREAD

**Issue by zhouluyao** [onevcat/VVDocumenter-Xcode#147] opened 2015-07-23 12:03 UTC
//
//  Header.h
//  Supplier
//
//  Created by luyao's IMac on 7/23/15.
//  Copyright (c) 2015 czDeveloper. All rights reserved.
//

#ifndef Supplier_Header_h
#define Supplier_Header_h

#pragma mark BillInfo
#define APP_GetBillCount                                 @"/getbillcount"
#define APP_GetBillCount_TAG                             3001

#define APP_GetFine_QuertByDate                          @"/getfine"
#define APP_GetFine_QuertByDate_TAG                      3002

#define APP_GetUncomfirmBill                            @"/getunconfirmbill"
#define APP_GetUncomfirmBill_TAG                        3003

#define APP_GetComfirmErrorBill                         @"/getconfirmerrorbill"
#define APP_GetComfirmErrorBill_TAG                     3004

#define APP_GetUnpayBill                                @"/getunpaybill"
#define APP_GetUnpayBill_TAG                            3005

#define APP_GetPayedAmount                              @"/getpayedamount"
#define APP_GetPayedAmount_TAG                          3006

#define APP_GetPayedBill                                @"/getpayedbill"
#define APP_GetPayedBill_TAG                            3007

#define APP_ComfirmBill                                 @"/confirmbill"
#define APP_ComfirmBill_TAG                             3008

#define APP_ComfirmErrorBill                            @"/confirmerrorbill"
#define APP_ComfirmErrorBill_TAG                        3009

#pragma mark MyInfo

**Comment by onevcat** [comment] 2015-08-21 01:38
I tried this snippets in several context but failed to reproduce it. If someone encountered the same issue, please leave a comment.
I will keep this issue open for some time.

**Comment by onevcat** [comment] 2015-09-11 07:54
Close it since not reproducible.

**Closed** 2015-09-11 07:54 UTC
